### PR TITLE
Bug/use fetch cache dependencies

### LINKED ISSUE #182: useFetch hook not re-running on dependency update to variable in cached url
**Describe the bug**
If the useFetch hook is set to watch changes to variables in the url/pat, the hook does not re-run 
if you update the variable to one that has already been cached.

**⚠️ Make a Codesandbox ⚠️**
https://codesandbox.io/s/peaceful-sound-e053d

**To Reproduce**
1. Click 'load post 2' button
2. Click 'load post 3' button
3. Click 'load post 1' button
4. The data is no longer updated and the hook never re-runs as all three possible urls have been cached.

**Expected behavior**
You would expect the hook to rerun and fetch the cached data for the individual path, not just the last one that was run.

I believe the bug was introduced with PR #171 - The hook functions as expected with caching turned off. It is also worth noting that line 402 in `src/__tests__/useFetch.test.tsx` in that same PR stops the rest of the test execution and could be the reason that this bug wasn't picked up through testing. By removing that line, the test fails.

### PR DESCRIPTION
**Pull request by maxquinn**
Fixes #182

### CODE REVIEW

**Comment by maxquinn** [comment]
@alex-cory It seems that the hook was fetching the cached data correctly, however as there was no state update, the return values were never updated client-side. I have fixed this by setting the `loading` state appropriately. 

I wonder if for future improvements we should look into migrating the "state" of `useFetch` to make use of react's `useReducer` hook? - https://reactjs.org/docs/hooks-reference.html#usereducer

File: src/useFetchArgs.ts [hunk 1]
```diff
@@ -89,44 +104,87 @@ export default function useFetchArgs(
...
 
   const dependencies = useMemo((): any[] | undefined => {
-    if (Array.isArray(optionsNoURLsOrOverwriteGlobalOrDeps)) return optionsNoURLsOrOverwriteGlobalOrDeps
+    if (Array.isArray(optionsNoURLsOrOverwriteGlobalOrDeps))
+      return optionsNoURLsOrOverwriteGlobalOrDeps
     if (Array.isArray(deps)) return deps
     return defaults.dependencies
   }, [optionsNoURLsOrOverwriteGlobalOrDeps, deps])
 
+  const useField = <DV = any>(
```
[the remark this answers is not in the document]
Comment (alex-cory) [reply src/useFetchArgs.ts]: A little confused why you did this. Also, this function is now getting recreated each time we rerender. Probably want to leave this outside `useFetchArgs`

**Comment by maxquinn** [comment]
Thanks for the review @alex-cory. I'll get these changes up today. Yeah most of this was prettier/eslint. Might need to tweak the config to your liking.

File: src/__tests__/useFetch.test.tsx [hunk 2]
```diff
@@ -369,61 +394,64 @@ describe('caching - useFetch - BROWSER', (): void => {
...
   })
 })
 
 describe('useFetch - BROWSER - with <Provider /> - Managed State', (): void => {
   const expected = { title: 'Alex Cory' }
+  const second = { title: 'Max Quinn' }
 
   const wrapper = ({ children }: { children?: ReactNode }): ReactElement => (
-    <Provider url='https://example.com'>{children}</Provider>
+    <Provider url="https://example.com">{children}</Provider>
```
[the remark this answers is not in the document]
Comment (maxquinn) [reply src/__tests__/useFetch.test.tsx]: Turns out prettier forces you to use double quotes in JSX and don't allow the ability to change this rule. Definitely in favour of canning it altogether if you are

**Comment by maxquinn** [comment]
If we wanted to enforce some sort of code style, it might be worth looking at one of the eslint style configs. https://www.npmjs.com/package/eslint-config-airbnb or https://github.com/standard/eslint-config-standard.

I'd be happy to implement one or just remove the prettier implementation altogether. Let me know :)

**Comment by maxquinn** [comment]
> If we wanted to enforce some sort of code style, it might be worth looking at one of the eslint style configs. https://www.npmjs.com/package/eslint-config-airbnb or https://github.com/standard/eslint-config-standard.
> 
> I'd be happy to implement one or just remove the prettier implementation altogether. Let me know :)

@alex-cory

**Comment by alex-cory** [comment]
apologies. I thought I posted this review yesterday^

**Comment by alex-cory** [comment]
> If we wanted to enforce some sort of code style, it might be worth looking at one of the eslint style configs. https://www.npmjs.com/package/eslint-config-airbnb or https://github.com/standard/eslint-config-standard.
> 
> I'd be happy to implement one or just remove the prettier implementation altogether. Let me know :)

Let's remove prettier all together. Let me take a look at the eslint style configs.

**Comment by alex-cory** [comment]
Bare with me, I'm doing this on vacation 🙏

**Comment by maxquinn** [comment]
> Bare with me, I'm doing this on vacation 🙏I'm back march 3rd but will try to get as much done as I can until then

No rush! enjoy your vacation.

File: src/__tests__/useFetch.test.tsx [hunk 3]
```diff
@@ -92,26 +95,26 @@ describe('useFetch - BROWSER - basic functionality', (): void => {
...
+      { wrapper: wrapper as React.ComponentType },
     )
 
-    var [request, response, loading, error] = result.current
+    const [request, , loading, error] = result.current
     expect(request.loading).toBe(true)
     expect(loading).toBe(true)
     expect(error).toBe(undefined)
     await waitForNextUpdate()
-    var [request, response, loading, error] = result.current
```
[the remark this answers is not in the document]
Comment (maxquinn) [reply src/__tests__/useFetch.test.tsx]: Yeah it was, I guess I'll just modify this so that they are assigned once.

[the remark this answers is not in the document]
Comment (maxquinn) [reply src/__tests__/useFetch.test.tsx]: image
Oh, this is is why it was destructured twice - from the `@testing-library/react-hooks` docs.

**Comment by alex-cory** [comment]
Let's try [eslint-config-standard])(https://github.com/standard/eslint-config-standard) and we can tweak it to our needs.

**Comment by maxquinn** [comment]
Ok, looks good. Are you happy for me to try and set it up in this PR?

**Comment by alex-cory** [comment]
Hmm.... preferably we do it in a separate PR, and revert the prettier changes (for example [these](https://github.com/alex-cory/use-http/pull/183/files#diff-8980cc2225b90d497e98b315804b64d0R29-R36)). If it's a lot easier/time efficient to revert those changes by implementing the eslint stuff in this PR, just go for it.

**Comment by maxquinn** [comment]
Ok no worries, I'll split it out into two separate PR's. Probably get to it tomorrow.

**Comment by alex-cory** [comment]
Thanks for all your hard work on this btw

**Comment by maxquinn** [comment]
Have created a draft PR (#188) with the standardjs config stuff. Let me know what you think and reverted the stylistic changes to this one. Let me know what you think @alex-cory

**Comment by alex-cory** [comment]
I have a few errands I gotta run, but gonna get to this today asap

File: src/__tests__/useFetch.test.tsx [hunk 4]
```diff
@@ -449,22 +448,75 @@ describe('useFetch - BROWSER - with <Provider /> - Managed State', (): void => {
...
+    })
+    await waitForNextUpdate()
+    expect(result.current.data).toEqual(second)
+  })
+
+  it('should fetch cached data when cached path is requested', async (): Promise<void> => {
+    const { result, waitForNextUpdate, rerender } = renderHook(
+      ({ initialValue }) =>
+        useFetch(
+          {
```
Comment (alex-cory) [inline src/__tests__/useFetch.test.tsx]: you really like having the options be on their own line huh. I guess I should be more open minded about this.

File: src/useFetch.ts [hunk 5]
```diff
@@ -83,13 +83,17 @@ function useFetch<TData = any>(...args: UseFetchArgs): UseFetch<TData> {
       const isCached = cache.has(requestID)
       const cachedData = cache.get(requestID)
       if (isCached && cachePolicy === CACHE_FIRST) {
+        setLoading(true)
```
Comment (alex-cory) [inline src/useFetch.ts]: We shouldn't need this. If the data is cached it should be immediate. After this get's merged I have a change that instead of caching the data, we cache the `response` which fixes other problems. Regardless, we don't need to modify state if it's cached.

File: src/useFetch.ts [hunk 6]
```diff
@@ -83,13 +83,17 @@ function useFetch<TData = any>(...args: UseFetchArgs): UseFetch<TData> {
...
         let age = Date.now() - whenCached
         if (cacheLife > 0 && age > cacheLife) {
           cache.delete(requestID)
           cache.delete(requestID + ':ts')
         } else {
-          return cachedData
+          res.current.data = cachedData
+          data.current = cachedData
+          setLoading(false)
+          return data.current
```
Comment (alex-cory) [inline src/useFetch.ts]: beautiful, we just need to not modify the state here. Unless for some reason we expect `loading` to be true for some reason (other than setting it to true above in your code change)

Comment (alex-cory) [reply src/useFetch.ts]: Once these things are resolved, I'll most likely merge this immediately.

Comment (alex-cory) [reply src/useFetch.ts]: Amazing work so far btw

Comment (maxquinn) [reply src/useFetch.ts]: The only reason I chose to toggle the `loading` state here is because if we don't modify the state, the hook never re-renders and so we cant listen for updates to data out the other end.

Comment (maxquinn) [reply src/useFetch.ts]: Hopefully that makes sense

File: src/__tests__/useFetch.test.tsx (hunk 4 above)
Comment (maxquinn) [reply src/__tests__/useFetch.test.tsx]: Can absolutely modify this to keep it consistent with the other tests. My bad

File: src/useFetch.ts (hunk 6 above)
Comment (alex-cory) [reply src/useFetch.ts]: ah! I see, hm.. let me think about this

**Comment by alex-cory** [comment]
Some tests were broken so had to revert. Specifically the timeout ones.  Hm... these tests are brittle right now. I don't think this was actually caused by your PR, so go ahead and create another PR and I'll get this merged. I think `setLoading` might need to be pulled out of the `finally` clause.

**Comment by maxquinn** [comment]
@alex-cory Ok so I should just make the same pull request? Do you want me to look at fixing the timeout test too?

**Comment by alex-cory** [comment]
That would be amazing. I'm back 100% tomorrow
